### PR TITLE
Feat: New rules; Object spacing, eol, jsx-no-bind, prefer-stateless-function, self-closing-comp

### PR DESCRIPTION
**Pull request by SvanBoxel**
Added 5 new rules to bring more consistency to your codebase.

1) **object-curly-spacing** _Error_
`const obj = { foo: { you: 'bar' } };`
insetad of 
`const obj = {foo: {you: 'bar' }};`
https://eslint.org/docs/rules/object-curly-spacing

2) **eol-last** _Error_
End each file with an empty line.
https://eslint.org/docs/rules/eol-last

3) **jsx-no-bind** _Warning_
Stop creating functions on every rerender!
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md

4) **prefer-stateless-function** _Warning_
Benefits from performance optimization
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md

5) **self-closing-comp** _Error_
Prevent extra closing tags for components
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md

All rules that generate an error have the autofix option.
The rules that generate a warning _don't_ have the autofix option. 

Also added the react rules to our spec definition.

### CODE REVIEW

**Comment by arkaitzgarro** [comment]
Technically I think this a breaking change. When the new version is released, ESLint will complain and stop the build (including ours), forcing developers to make a change on the source code or downgrade the version to be able to proceed.

I think it should be a major version even though it has an automagic option. Do you agree @SvanBoxel?

**Comment by SvanBoxel** [comment]
Technically I do. However, check out eslints own standard config repo. It does look like they increment the minor version when adding a new rule. (However, sometimes they increment the major version.)
https://github.com/standard/eslint-config-standard/ https://github.com/standard/eslint-config-standard/commits/v6.2.0?after=5eed6cd11bc77866fe719ee117918d0570e3a71c+34

**Comment by SvanBoxel** [comment]
If we're going to increment the major version, maybe we should add more rules first to prevent we have to release _another_ major version in a couple of weeks.

**Comment by SvanBoxel** [comment]
@arkaitzgarro I'm going to add more rules and then we just make it a major release. Standby.

**Comment by SvanBoxel** [comment]
My proposal is to use increase the minor version for updates that trigger new warnings, and a major version increase for updates that trigger new errors.

**Comment by arkaitzgarro** [comment]
OK, so we can consider these changes as BREAKING because of `'react/self-closing-comp': 'error'`. In that case, to make the magic happen, we must include `"BREAKING CHANGE: message about the breaking change"` on the commit message. Can you please rebase and add the message?

**Comment by SvanBoxel** [comment]
Yes, break all the things. I'll rebase.

**Comment by SvanBoxel** [comment]
@arkaitzgarro Rebase is done.

**Pull request merged**
